# 9 Sensibilisation

## Défi
Quel est le meilleur moyen de sensibiliser aux problèmes qui sous-tendent la Transition dans votre quartier ? 

## Description
Les activités de sensibilisation sont nombreuses et variées : elles couvrent tout ce qui permet aux personnes de comprendre, d'apprendre et de faire quelque chose de nouveau, d'imaginer l'avenir, de travailler à la façon de changer certains aspects de leur vie ou de parler à quelqu'un de ce qu'elles ont fait... tout cela fait partie du processus de sensibilisation sur les besoins de la Transition. 

## Solution
Organisez toujours des activités de sensibilisation qui ont été pensées pour les habitants de votre quartier, que ce soit au niveau de la thématique, du style ou du langage. Prévoyez un temps de digestion de l'information, un moment pour exprimer et partager les ressentis. Le but est que les personnes présentes soient ensuite capables de décider seules de ce qu'elles pourraient faire.

## Description complète
Les activités de sensibilisation sont nombreuses et variées : elles couvrent tout ce qui permet aux personnes de comprendre, d'apprendre et de faire quelque chose de nouveau, d'imaginer l'avenir, de travailler à la façon de changer certains aspects de leur vie ou de parler à quelqu'un de ce qu'elles ont fait... tout cela fait partie du processus de sensibilisation sur les besoins de la Transition. De grands événements, ouverts à tous et très médiatisés, fonctionneront à certains endroits et pour certaines personnes, alors qu'ailleurs, il vaudrait mieux utiliser une approche plus douce, nouer le dialogue avec les groupes existants et éventuellement soutenir leur travail. Vancouver en Transition, par exemple, a passé une année à faire connaître et à soutenir les événements d'autres groupes avant de commencer à organiser les siens.

**Transition en action : Campagnes de sensibilisation à Ambleside **
_par Steph Bradley_
_À Ambleside, en Cumbria, s'est formée une association appelée AAA, l'Association des jardins communautaires d'Ambleside. Lorsque la fondatrice de l'association a quitté Lewes pour s'installer à Ambleside, elle espérait y retrouver une initiative de Transition. N'en ayant pas trouvé, elle s'est donc fixé l'objectif d'en lancer une, à la condition que celle-ci soit véritablement ouverte à tous. Il lui fallait donc trouver le moyen d'obtenir un groupe diversifié dès le départ. Elle a tout d'abord passé beaucoup de temps à être simplement à l'écoute : quelles sont les préoccupations du village ? Y a-t-il une passion commune ? Elle s'est vite rendu compte qu'Ambleside n'avait jamais disposé de jardins communautaires, alors que les habitants en avaient envie. Elle a donc parcouru le village et s'est mise à parler aux gens, à tous types de personnes, non pas de la Transition, mais de ces jardins. Elle a discuté avec les personnes âgées, celles qui étaient là depuis des générations, avec les conseillers, les femmes au foyer, les entrepreneurs locaux, les jeunes, les travailleurs pour former un groupe dont la tâche serait de trouver des jardins pour Ambleside. Lorsque je m'y suis rendu en 2010, les choses bougeaient vite et le groupe avait déjà identifié ou reçu des offres pour trois sites._

_Les membres d'AAA ont déjà organisé des journées portes ouvertes pour présenter tout ce qu'ils ont fait dans le but de rendre leurs maisons moins énergivores. Ils ont également lancé des campagnes de sensibilisation en partenariat avec la bibliothèque locale qui a depuis inauguré un espace ouvert à l'arrière de son local afin d'y cultiver un petit potager collectif. Alors qu'un ouvrier du bâtiment semi-retraité du groupe se plaignait de ne toujours pas avoir de jardin à lui, le groupe s'est rassemblé et l'a aidé à transformer sa cour en un paradis de jardinier. La langue commune d'Ambleside en Transition, ce sont les jardins communautaires, le reste naît de façon ponctuelle en fonction des envies et des intérêts.  _

Pour réussir une campagne de sensibilisation, il est crucial de bien comprendre les autres habitants de votre région. Il se peut que des personnes impliquées dans la Transition aient déménagé récemment. Si c'est le cas, assurez-vous d'être en contact avec les personnes et les groupes qui connaissent déjà la région, écoutez leurs conseils avant d'entamer les activités visibles. Les premières impressions comptent beaucoup et commencer par marcher sur les plates-bandes de groupes existants peut s'avérer long et difficile à rectifier par la suite. 

**Des campagnes de sensibilisation qui s'adaptent au public cible**
Il est nécessaire de comprendre le processus du changement pour concevoir des activités de sensibilisation efficaces. Il ne faudrait pas, comme c'est souvent le cas, croire qu'il suffise de faire comprendre aux gens que le système actuel ne fonctionne pas pour qu'ils prennent automatiquement les mesures nécessaires pour le changer. Visionner _The end of suburbia_ (voir la section Ressources) ne va pas systématiquement pousser les gens à isoler leur loft et à bêcher leur jardin dès le lendemain. Les spécialistes du changement de comportement nous brossent un tableau bien différent. Ils nous disent que nous passons par plusieurs étapes entre le jour où nous apprenons que quelque chose ne fonctionne pas et le moment où nous changeons réellement de comportement. Carle DiClemente, spécialiste des dépendances, les appelle « les étapes du changement »<sup>[1](#note)</sup>. Il explique qu'à chacune de ces étapes, les gens éprouvent des besoins très différents et qu'il faut donc adapter la communication en conséquence. De quoi les personnes ont-elles besoin à chacune de ces étapes ? 

![Comment adapter vos campagnes de sensibilisation](https://raw.githubusercontent.com/reseautransitionwb/reseau_transition/master/contributions/Adaptation%20des%20campagnes%20de%20sensibilisation.png)

Il faut également garder à l'esprit que tout le monde n'apprend pas de la même façon. Certaines personnes apprennent et digèrent l'information intellectuellement, après avoir été exposées à des idées, concepts et informations écrites ou orales. D'autres réagissent plutôt émotionnellement, en s'impliquant au nom de ce qui les préoccupe, ce qu'elles craignent ou espèrent. Par exemple, le film de Rebecca Hosking _The message in the waves_ a eu un impact énorme sur son village, Modbury, qui a fini par interdire les sacs en plastique. D'autres personnes encore ont besoin d'apprendre d'une façon plus physique, en faisant quelque chose : construire, planter, essayer différents scénarios... Si vous parvenez à concevoir des événements qui, d'une façon ou d'une autre, parlent à ces différents types de personnes, vous aurez beaucoup plus de chances de sensibiliser en profondeur, comme vous le souhaitiez. 

Pour que vos événements restent aussi accessibles que possible, rappelez-vous que ces différents types de personnes viennent à des moments différents de la journée et de la semaine, et que certaines ne pourront pas venir à vos événements à certains moments ou à certains endroits. Réfléchissez à la meilleure solution pour les parents, les enfants, les personnes âgées, les travailleurs, ceux dont la langue maternelle n'est pas le français, ceux qui ont un handicap physique ou qui viennent d'une culture différente. Essayez également de faire preuve de créativité en choisissant les thèmes de vos événements, car différents sujets intéresseront des publics différents. Cela conférera à votre initiative un avantage, une plus grande pertinence pour plus de personnes. Au sein de votre initiative de Transition, il y aura des personnes qui auront une passion et des compétences dans le domaine de l'alimentation, de la construction, des arts, de l'artisanat, de la politique, etc. : tentez d'intégrer un peu de cela dans votre programme de sensibilisation. 

Une stratégie très utile pour votre initiative pourrait être de concevoir vos événements de telle sorte que les élus locaux s'y investissent. Avant les élections nationales de 2010, beaucoup d'initiatives de Transition, dont Luton en Transition, ont organisé des événements liés à la campagne électorale et invité les candidats locaux à débattre de sujets liés à la Transition [2]. Belsize en Transition, à Londres, a eu l'idée de convier des hommes politiques locaux à prendre place dans un fauteuil à l'avant de la salle pendant la projection d'un film et de leur demander ensuite de donner leur avis. 

**Transition en action : La foire urbaine verte de Belsize en Transition  **
*par Sarah Nicholl*

*La foire urbaine verte est l'apogée de l'éco-semaine, un événement annuel organisé par Belsize en Transition qui a lieu le long de la grande zone pavée de Haverstock Hill dans Londres NW3, en face du métro du parc de Belsize. La foire verte dure tout un samedi et s'organise autour d'une série de stands fascinants, d'activités physiques et d'événements divertissants (démonstrations d'apiculture, présence des animaux de basse-cour de la ferme urbaine Freightliners, construction d'une serre avec des bouteilles en plastique, atelier réparation de vélos avec Dr Bike, artisanat, arts et bancs tricotés, terrain de jeux pour les enfants sur le thème de l'abeille, piñata en forme d'abeille, peinture, musique, construction d'une ruche en torchis, balade du butinage, atelier cuisine et de dégustation avec les aliments rapportés suivant les conseils du chef Sarah Moore, course divertissante de 5 km, pâtisseries, gâteaux, chutneys et confitures locales et de saison, énergie et panneaux solaires de Belsize, pizza maison cuite dans un four en torchis, concours de légumes bizarres, camp climat...)*

_Lors des campagnes de sensibilisation, l'accent ne doit pas toujours être mis sur le fait de parler et d'expliquer les choses aux gens... il est essentiel de les écouter également. Une femme d'un petit village aux États-Unis a expliqué que comme elle ne vivait dans son village que depuis 17 ans (!), elle ne se sentait pas légitime pour organiser des événements et des conférences, car cela aurait pu sembler présomptueux et rebuter certaines personnes. Pour sensibiliser, elle a donc choisi d'inclure dans un maximum de conversations possibles la phrase « à l'époque de la fin du pétrole bon marché », et de s'impliquer parallèlement dans un grand nombre d'activités du quartier. Son amie nous a confié que nous ne pouvions pas nous imaginer à quel point elle était douée pour glisser cette phrase dans une conversation quel que soit le sujet ou la personne avec qui elle parle... personnes qui finissent par reprendre la phrase ! La campagne de sensibilisation doit également faire sens pour différentes personnes. Il peut donc être utile de travailler en partenariat avec d'autres organisations. Cette méthode vous permettra de mieux cerner les atouts et les compétences des habitants de votre quartier._

**Transition en Action : Caminata de Barcelone en Transition **
_par Claudia French_

_Barcelona-en-Transición (Barcelone en Transition) a organisé une randonnée (Caminata) dans la région de Poble Sec et de la colline du Montjuïc avec l'aide d'habitants de la région, d'organisations et de petites entreprises. Après environ quatre mois de préparation et de reconnaissance sur le terrain, nous avons visité, un samedi de septembre 2010, plusieurs lieux d'intérêt liés au mouvement international de la Transition. Nous sommes allés, par exemple, dans des jardins collectifs, à la rencontre d'artisans locaux et d'artistes qui utilisent des matériaux locaux (bois, laine, cuir, métal,...), ainsi que dans des magasins, cafés et coopératives alimentaires qui vendent des produits locaux, biologiques et/ou sans emballage. _

_Les Caminatas que nous organisons donnent aux habitants de différents quartiers de Barcelone l'occasion de mieux connaître leur région et de mieux comprendre le mouvement de la Transition et ses objectifs. Nous organisons ces événements à intervalles réguliers et notre but est de nous rendre dans tous les quartiers de Barcelone. Nous terminons chaque Caminata par un pique-nique partagé où chacun amène des boissons et des plats locaux. Nous en profitons pour reparler de l'événement, répondre aux questions et finalement passer du bon temps et faire connaissance. Un peu de plaisir local sans recourir au pétrole... ne nous privons pas de célébrer !_

Voici d'autres propositions qui pourraient vous intéresser :

**Prévoyez un temps de digestion**: Prévoyez un temps où les personnes pourront s'exprimer et s'écouter après la projection d'un film ou une conférence. Ponctuez également ce moment d'une session de questions-réponses. Demandez à avoir un retour d'informations et d'idées pour que tout le monde puisse entendre ce que les autres pensent ou ressentent. Beaucoup de groupes fonctionnent avec des post-its et demandent au public d'y écrire ses idées, avant de les rassembler. Vous pourriez également prévoir une grande feuille de papier, collée sur un mur, où tout le monde pourrait écrire et dessiner. 

**Donnez l'information, mais n'expliquez pas aux gens ce qu'ils doivent faire** : Un principe clé de la Transition est de donner une information de qualité et d'ensuite faire confiance aux gens et se dire qu'ils trouveront leur propre moyen d'agir. Vous pouvez parler de vos réactions personnelles, de ce que vous avez ressenti et de ce que vous avez changé. Mais dire aux autres ce qu'ils « devraient » faire a un côté condescendant et inapproprié qui risque plutôt de provoquer une résistance au changement. 

Il est important de se rendre compte qu'en évoluant, votre initiative de Transition va changer sa façon de concevoir la sensibilisation. Au cours des deux premières des cinq étapes décrites dans ce livre, « démarrer » et « renforcer », parler du pic pétrolier et du changement climatique constitue un catalyseur puissant et vous permet d'aborder de façon efficace la problématique de la résilience de votre quartier. Une fois arrivés à la quatrième étape, « construction », vous vous rendrez compte que la plupart des habitants de votre quartier se seront fait une idée sur la question et qu'insister sur ce point crée davantage de division que d'engagement. Il pourrait être alors plus productif de mettre l'accent sur la résilience économique et la mise en place de nouveaux projets et de nouvelles entreprises.

<a id="note"> </a>
## Notes

[1] DiClemente, C.C. (2003) Addiction and change: How addictions develop and addicted people recover. Guilford Press.

[2] [http://tinyurl.com/ykcput8](http://tinyurl.com/ykcput8)

## Sources
Traduit du [Transition Companion](https://www.transitionnetwork.org/transition-companion) écrit par [Rob Hopkins](https://www.transitionnetwork.org/about/people/staff-and-key-contributors). Traduction par [Caroline Durieux](http://www.reseautransition.be/articles/author/caroline-durieux/) selon les termes de la licence Creative Commons BY-NC-SA.

Publié par [François-Olivier Devaux](mailto:francois@reseautransition.be) via [Réseau Transition Belgique](http://www.reseautransition.be/) selon les termes de la licence Creative Commons BY-NC-SA.

Ce texte est hébergé sur la plate-forme collaborative Multibao. Vous souhaitez l'éditer ou le voir apparaître sur votre site internet ? Rendez-vous sur [www.multibao.org](www.multibao.org)
